# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999390de3b181e10299673bce43b4721fa5a108136b4016a81aad8b06fcaba8bdda5967d62be65f4d053ae502c523a2380837db691bd173de0c199a6c461805d

test:
  secret_key_base: 45b3bb831639d8654db30a3dede75ebb3b5af985cabb969dbcecd0329049ae79583932ae66b542c50ec0c7b119cb13a7ce0c904295de145cc53ae0e74c61ba19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
